/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "ada@example.com",
                     *       "password": "S3cureP@ssw0rd"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "token": "eyJhbGciOiJIUzI1Ni...",
                         *       "user": {
                         *         "created_at": "2025-10-01T10:00:00Z",
                         *         "deleted_at": null,
                         *         "email": "ada@example.com",
                         *         "id": "00000000-0000-0000-0000-000000000000",
                         *         "name": "Ada Lovelace",
                         *         "provider": "local",
                         *         "provider_id": null,
                         *         "updated_at": "2025-10-01T10:00:00Z"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout acknowledged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "created_at": "2025-10-01T10:00:00Z",
                         *       "deleted_at": null,
                         *       "email": "ada@example.com",
                         *       "id": "00000000-0000-0000-0000-000000000000",
                         *       "name": "Ada Lovelace",
                         *       "provider": "local",
                         *       "provider_id": null,
                         *       "updated_at": "2025-10-01T10:00:00Z"
                         *     }
                         */
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "ada@example.com",
                     *       "name": "Ada Lovelace",
                     *       "password": "S3cureP@ssw0rd"
                     *     }
                     */
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description User registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "token": "eyJhbGciOiJIUzI1Ni...",
                         *       "user": {
                         *         "created_at": "2025-10-01T10:00:00Z",
                         *         "deleted_at": null,
                         *         "email": "ada@example.com",
                         *         "id": "00000000-0000-0000-0000-000000000000",
                         *         "name": "Ada Lovelace",
                         *         "provider": "local",
                         *         "provider_id": null,
                         *         "updated_at": "2025-10-01T10:00:00Z"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Email already in use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "created_at": "2025-10-01T10:00:00Z",
                         *         "deleted_at": null,
                         *         "description": "Prepare milestones for the product launch.",
                         *         "id": "00000000-0000-0000-0000-000000000000",
                         *         "name": "Launch Planning",
                         *         "theme_color": "#3498db",
                         *         "updated_at": "2025-10-01T10:00:00Z",
                         *         "user_id": "11111111-1111-1111-1111-111111111111"
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "description": "Prepare milestones for the product launch.",
                     *       "name": "Launch Planning",
                     *       "theme_color": "#3498db"
                     *     }
                     */
                    "application/json": components["schemas"]["ProjectCreateRequest"];
                };
            };
            responses: {
                /** @description Project created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "created_at": "2025-10-01T10:00:00Z",
                         *       "deleted_at": null,
                         *       "description": "Prepare milestones for the product launch.",
                         *       "id": "00000000-0000-0000-0000-000000000000",
                         *       "name": "Launch Planning",
                         *       "theme_color": "#3498db",
                         *       "updated_at": "2025-10-01T10:00:00Z",
                         *       "user_id": "11111111-1111-1111-1111-111111111111"
                         *     }
                         */
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 00000000-0000-0000-0000-000000000000 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "created_at": "2025-10-01T10:00:00Z",
                         *       "deleted_at": null,
                         *       "description": "Prepare milestones for the product launch.",
                         *       "id": "00000000-0000-0000-0000-000000000000",
                         *       "name": "Launch Planning",
                         *       "theme_color": "#3498db",
                         *       "updated_at": "2025-10-01T10:00:00Z",
                         *       "user_id": "11111111-1111-1111-1111-111111111111"
                         *     }
                         */
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 00000000-0000-0000-0000-000000000000 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "description": "Updated description",
                     *       "name": "Launch Planning - Updated",
                     *       "theme_color": "#2ecc71"
                     *     }
                     */
                    "application/json": components["schemas"]["ProjectUpdateRequest"];
                };
            };
            responses: {
                /** @description Project updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "created_at": "2025-10-01T10:00:00Z",
                         *       "deleted_at": null,
                         *       "description": "Prepare milestones for the product launch.",
                         *       "id": "00000000-0000-0000-0000-000000000000",
                         *       "name": "Launch Planning",
                         *       "theme_color": "#3498db",
                         *       "updated_at": "2025-10-01T10:00:00Z",
                         *       "user_id": "11111111-1111-1111-1111-111111111111"
                         *     }
                         */
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 00000000-0000-0000-0000-000000000000 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project soft deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Set to true to list progress entries instead of tasks */
                    progress?: boolean;
                    /** @description Optional task id to filter progress */
                    task_id?: string;
                };
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List tasks or progress entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][] | components["schemas"]["Progress"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "due_date": "2025-10-10T10:00:00Z",
                     *       "status": "pending",
                     *       "title": "Define launch checklist"
                     *     }
                     */
                    "application/json": components["schemas"]["TaskCreateRequest"];
                };
            };
            responses: {
                /** @description Task created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "created_at": "2025-10-01T10:00:00Z",
                         *       "deleted_at": null,
                         *       "due_date": "2025-10-10T10:00:00Z",
                         *       "id": "22222222-2222-2222-2222-222222222222",
                         *       "project_id": "00000000-0000-0000-0000-000000000000",
                         *       "status": "pending",
                         *       "title": "Define launch checklist",
                         *       "updated_at": "2025-10-01T10:00:00Z"
                         *     }
                         */
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                    /** @example 00000000-0000-0000-0000-000000000000 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "due_date": "2025-11-01T10:00:00Z",
                     *       "status": "in_progress",
                     *       "title": "Refine checklist"
                     *     }
                     */
                    "application/json": components["schemas"]["TaskUpdateRequest"];
                };
            };
            responses: {
                /** @description Task updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "created_at": "2025-10-01T10:00:00Z",
                         *       "deleted_at": null,
                         *       "due_date": "2025-10-10T10:00:00Z",
                         *       "id": "22222222-2222-2222-2222-222222222222",
                         *       "project_id": "00000000-0000-0000-0000-000000000000",
                         *       "status": "pending",
                         *       "title": "Define launch checklist",
                         *       "updated_at": "2025-10-01T10:00:00Z"
                         *     }
                         */
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                    /** @example 00000000-0000-0000-0000-000000000000 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task soft deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        LoginRequest: {
            /** @example ada@example.com */
            email: string;
            /** @example S3cureP@ssw0rd */
            password: string;
        };
        Progress: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: uuid */
            id: string;
            note?: string | null;
            /** Format: int32 */
            progress: number;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            task_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProgressCreateRequest: {
            /** @example Halfway done - waiting on review */
            note?: string | null;
            /**
             * Format: int32
             * @example 75
             */
            progress: number;
        };
        ProgressUpdateRequest: {
            note?: string | null;
            /** Format: int32 */
            progress?: number | null;
        };
        Project: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            description?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            theme_color: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            user_id: string;
        };
        ProjectCreateRequest: {
            /** @example Prepare milestones for the product launch. */
            description?: string | null;
            /** @example Launch Planning */
            name: string;
            /** @example #3498db */
            theme_color?: string | null;
        };
        ProjectUpdateRequest: {
            /** @example Updated description */
            description?: string | null;
            /** @example Launch Planning */
            name?: string | null;
            /** @example #2ecc71 */
            theme_color?: string | null;
        };
        RegisterRequest: {
            /** @example ada@example.com */
            email: string;
            /** @example Ada Lovelace */
            name: string;
            /** @example S3cureP@ssw0rd */
            password: string;
        };
        Task: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            due_date?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            status: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        TaskCreateRequest: {
            /**
             * Format: date-time
             * @example 2025-10-10T10:00:00Z
             */
            due_date?: string | null;
            /** @example pending */
            status?: string | null;
            /** @example Define launch checklist */
            title: string;
        };
        TaskUpdateRequest: {
            /**
             * Format: date-time
             * @example 2025-11-01T10:00:00Z
             */
            due_date?: string | null;
            status?: string | null;
            title?: string | null;
        };
        User: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
            provider: string;
            provider_id?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
