import fs from "fs";
import path from "path";

const root = process.cwd();
const openapiPath = path.join(root, "openapi.json");
const outDir = path.join(root, "src/schemas/generated");
const outFile = path.join(outDir, "api-schemas.ts");

function ensureDir(dir) {
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch (e) {
    // ignore
  }
}

function toZod(schema, name, components) {
  if (!schema) return "z.any()";
  if (schema.$ref) {
    const ref = schema.$ref.replace('#/components/schemas/', '');
    return `z.lazy(() => ${ref}Schema)`;
  }
  const t = schema.type;
  if (!t) {
    // fallback
    return "z.any()";
  }
  if (t === 'string') {
    let base = 'z.string()';
    if (schema.format === 'date-time') base = 'z.string().datetime()';
    if (schema.nullable) base += '.nullable()';
    return base;
  }
  if (t === 'integer' || t === 'number') return 'z.number()';
  if (t === 'boolean') return 'z.boolean()';
  if (t === 'array') {
    const item = toZod(schema.items, name, components);
    return `z.array(${item})`;
  }
  if (t === 'object') {
    const props = schema.properties || {};
    const required = schema.required || [];
    const lines = Object.keys(props).map((k) => {
      const propSchema = props[k];
      const expr = toZod(propSchema, k, components);
      const isRequired = required.includes(k);
      const optionalExpr = isRequired ? expr : `${expr}.optional()`;
      const exampleComment = propSchema && propSchema.example !== undefined ? ` // example: ${JSON.stringify(propSchema.example)}` : '';
  return `    ${k}: ${optionalExpr},${exampleComment}`;
    });
  return `z.object({\n${lines.join('\n')}\n  })`;
  }
  return 'z.any()';
}

function generate() {
  if (!fs.existsSync(openapiPath)) {
    console.error('openapi.json not found at', openapiPath);
    process.exit(2);
  }
  const doc = JSON.parse(fs.readFileSync(openapiPath, 'utf-8'));
  const components = (doc.components && doc.components.schemas) || {};
  ensureDir(outDir);

  let output = `/* This file is generated by scripts/generate-zod.js */\nimport { z } from 'zod'\n\n`;

  // We'll generate concrete schemas; use z.lazy for $ref references so order doesn't matter

  // Now generate concrete schemas (overwrite placeholders)
  Object.keys(components).forEach((name) => {
    const schema = components[name];
    const zodExpr = toZod(schema, name, components);
    output += `export const ${name}Schema = ${zodExpr};\n\n`;
  });

  // Export a components object for compatibility
  output += `export const components = { schemas: {\n`;
  Object.keys(components).forEach((name) => {
    output += `  ${name}: ${name}Schema,\n`;
  });
  output += `} } as const;\n`;

  fs.writeFileSync(outFile, output, 'utf-8');
  console.log('Wrote', outFile);
}

try {
  generate();
} catch (err) {
  console.error(err);
  process.exit(1);
}
